apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-service-a
spec:
  replicas: {{ .Values.serviceA.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-service-a
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-service-a
    spec:
      containers:
      - name: service-a
        image: {{ .Values.serviceA.image.repository }}:{{ .Values.serviceA.image.tag }}
        ports:
        - containerPort: {{ .Values.serviceA.service.targetPort }}
