apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service-a
spec:
  type: {{ .Values.serviceA.service.type }}
  ports:
  - port: {{ .Values.serviceA.service.port }}
    targetPort: {{ .Values.serviceA.service.targetPort }}
  selector:
    app: {{ .Chart.Name }}-service-a


